name: AskRose
markdown: redcarpet
pygments: false
safe: false
asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: assets       # Default = nil
  gzip: false